apiVersion: v2
name: product-service
description: A Helm chart for product-service with PostgreSQL sidecar database
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservice
  - product-service
  - spring-boot
  - postgresql
  - sidecar
home: https://github.com/your-org/microservice-testing-lab
sources:
  - https://github.com/your-org/microservice-testing-lab
maintainers:
  - name: Your Name
    email: your.email@example.com