server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0
        - id: notification-service
          uri: http://notification-service:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.kb.gateway_service: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/users-db
    username: user
    password: pass

