version: '3.8'

services:
  postgres-user:
    image: postgres:14
    environment:
      POSTGRES_DB: users-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:14
    environment:
      POSTGRES_DB: products-db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    depends_on:
      - postgres-user
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/users-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  product-service:
    build: ./product-service
    depends_on:
      - postgres-product
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-product:5432/products-db
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_pass

volumes:
  postgres-user-data:
  postgres-product-data:
