spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products-db
    username: product_user
    password: product_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-product:5432/products-db
    username: product_user
    password: product_pass

---

spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://localhost:5432/products-db
    username: product_user
    password: product_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

