package com.kb.synthetic.model.enums;

public enum FlowType {
    PRODUCT_BROWSE,
    ADD_TO_CART,
    CHECKOUT,
    PAYMENT,
    ORDER_CONFIRMATION,
    USER_REGISTRATION,
    USER_LOGIN,
    PRODUCT_SEARCH,
    WISHLIST_MANAGEMENT,
    ORDER_TRACKING,
    RETURN_PROCESS,
    REVIEW_SUBMISSION,
    CUSTOMER_SUPPORT,
    INVENTORY_CHECK,
    PRICE_COMPARISON
}
