server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5435/notifications-db
    username: notification_user
    password: notification_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  profiles:
    active: default

logging:
  level:
    com.kb.notification_service: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-notification:5432/notifications-db
    username: notification_user
    password: notification_pass

---

spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications-db
    username: notification_user
    password: notification_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

