spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users-db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-user:5432/users-db
    username: user
    password: pass

