package com.kb.jarvis.core.model;

public enum ActionType {
    RUN_TESTS, 
    RUN_PERFORMANCE_TESTS,
    RUN_SECURITY_TESTS,
    RUN_INTEGRATION_TESTS,
    RUN_ISOLATED_TESTS,
    RUN_CHAOS_TESTS,
    ANALYZE_FAILURES, 
    GENERATE_TESTS, 
    OPTIMIZE_TESTS, 
    HEALTH_CHECK, 
    MONITOR_SYSTEM,
    GENERATE_REPORT,
    REQUEST_CLARIFICATION,
    QUEUE_ACTION,
    SELF_HEAL, 
    SCALE_RESOURCES,
    UNKNOWN
} 